---
title: "Poc Cover Data with Biogeochem Params and Recruit Counts"
author: "Hannah Merges"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```

### Load libraries 
```{r}
library(tidyverse)
library(here)
library(ggrepel)
library(patchwork)
library(tidytext)
library(AICcmodavg)
library(kableExtra)
library(PNWColors)
library(factoextra)
library(devtools)
library(ggbiplot)
library(car)
```


### Load Data
```{r}
EnvData_wrecruitcounts <- read_csv(here::here("Data", "CommComp_recruit_seasonavg_envdata.csv"))

Poc_cover_data <- read_csv(here::here("Data", "Species_Composition_2022_Danielle.csv"))

#PercentCover <- read_csv("https://raw.githubusercontent.com/dbarnas/Community_Functional_Diversity/main/Data/Full_Metadata.csv")

PercentCover3 <- read_csv(here::here("Data", "PercentCover3.csv"))

RecruitmentCounts2.1 <- read_csv((here::here("Data", "RecruitmentCounts2.1.csv")))
```

## December, 2025: 

### Tidy data and join in DMB's Poc cover data 
-  a) filter out the sand and hard substrate categories and 
-  b) sum the totals by cowtagid to get percent cover of the biotics 
-  c) calcualte percent cover of P. acuta based on total amount of biotics in the area 
-  Add in 0s for the cowtags that don't have P acuta counts (confirmed with DMB, August 2024)
```{r}

#######################
## November, 2024 update 
######################

Corals <- c("Pocillopora acuta","Porites rus","Montipora verrilli","Montipora setosa","Montipora grisea","Porites irregularis","Porites lobata","Pocillopora verrucosa","Pavona chiriquiensis","Pavona cactus","Leptastrea transversa","Acropora","Acropora pulchra","Montipora capitata")

## creating df of just corals using DMB's df + new "Corals" only df 
df_corals <- Poc_cover_data %>% 
  filter(Taxa %in% Corals, 
         Location %in% c("Cabral", "Varari")) %>% 
  filter(Date!="7/19/22"|CowTagID!="C8") %>% 
  group_by(CowTagID) %>% 
  summarize(coral_counts = sum(SpeciesCounts)) 

## filtering out just P. acuta 
df_Pacuta <- Poc_cover_data %>% 
  filter(Taxa == "Pocillopora acuta", 
         Location %in% c("Cabral", "Varari")) %>% 
  filter(Date!="7/19/22"|CowTagID!="C8") %>% 
  group_by(CowTagID) %>% 
  summarize(Pacuta_counts = sum(SpeciesCounts)) ## getting a column of just P acuta counts 

## filtering out sand, bare rock, rubble, and maya's locations so that left with just living orgs 
Poc_cover_data2 <- Poc_cover_data %>% 
  dplyr::select(!c("Date", "PhotoNum", "Notes")) %>% 
  filter(Taxa!="Bare Rock",Taxa!="Sand",Taxa!="Rubble", Location!="Varari_Maya") %>% 
  group_by(CowTagID) 

## getting species count for all biotic orgs 
Poc_cover_data3 <- Poc_cover_data2 %>% 
  dplyr::summarise(total_count_biotics = sum(SpeciesCounts)) %>% 
  filter(CowTagID!="VSEEP") ## missing C14 

## getting just P acuta counts 
## NOTE: not all CowTagID have P acuta present 
Poc_cover_data4 <- Poc_cover_data2 %>% 
  filter(Taxa=="Pocillopora acuta") %>% 
  group_by(CowTagID) %>% 
  mutate(SpeciesCounts_Poc = SpeciesCounts) %>% 
  dplyr::select(!SpeciesCounts)
 
### joins correlated biotics counts for that CowTag -- only has CowTagIDs with P. acuta, missing data from CowTags without P. acuta  
Poc_cover_data5 <- Poc_cover_data4 %>% 
  left_join(Poc_cover_data3) %>% 
  group_by(CowTagID, Location, SpeciesCounts_Poc,total_count_biotics) %>% 
  dplyr::summarise(percent_cover = (SpeciesCounts_Poc/total_count_biotics)*(100)) 

##########################################
### join together with recruit count env data df and then make sure to add in the zeros for P acuta cowtags 
##########################################
EnvData_wPocCover <- EnvData_wrecruitcounts %>% 
  full_join(Poc_cover_data5) %>% 
  mutate(percent_cover = ifelse(is.na(percent_cover), 0, percent_cover)) %>% ###  ADD IN ZERO FOR COWTAGS WITHOUT P ACUTA COUNTS 
  write_csv(here::here("Data", "EnvData_wPocCover.csv"))

##########################################
## using Poc data WITH hard substrate and sand etc 
###########################################
Poc_cover_data_withhardsub <- Poc_cover_data %>% 
  dplyr::select(!c("Date", "PhotoNum", "Notes")) %>% 
  filter(Location!="Varari_Maya") %>% 
  group_by(CowTagID) 
  
###########################
## creating "full" datatset combining all the necessary info for env parameters, settlement counts, percent cover of adult coral, etc
###########################

#full <- Poc_cover_dataedit %>% 
#  left_join(df_Pacuta) %>% 
#  left_join(df_corals) %>% 
#  filter(!CowTagID %in% c("CSEEP","VSEEP")) %>% 
 # mutate(Pacuta_counts = ifelse(is.na(Pacuta_counts), 0, Pacuta_counts), 
      #   coral_counts = ifelse(is.na(coral_counts), 0, coral_counts)) %>%
 # mutate(pacuta_cover = (Pacuta_counts/total_counts)*100, 
     #    coral_percentcover = (coral_counts/total_counts)*100) %>% 
#  left_join(SettlementDF_Full) %>% ## need to bring/load this dataset at beginning of script!! 
 # write_csv(here::here("Data", "full.csv"))

#full2 <- full %>% 
 # group_by(Location) %>% 
 # summarize(totalPacuta_site = sum(Pacuta_counts), 
        #    totalcoralcover_site = sum(coral_counts))

#full3 <- full2 %>% 
 # group_by(Location) %>% 
 # summarize(totalPacuta_site_percent = (totalPacuta_site/totalcoralcover_site)*100)

```

